#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-v2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "fabdae29169d4b589ab8215ddbfe478c" }
]

[assets]
directory = "./public"
